export   const allItems = [
    {_id: "100" , title: "All Departments"},
    {_id: "101" , title: "Automotive"},
    {_id: "102" , title: "Baby"},
    {_id: "103" , title: "Beauty & Personal Care"},
    {_id: "104" , title: "Books"},
    {_id: "105" , title: "Boy's Fashion"},
    {_id: "106" , title: "Computers"},
    {_id: "107" , title: "Deals"},
    {_id: "108" , title: "Digital Music"},
    {_id: "109" , title: "Electronics"},
    {_id: "110" , title: "Girl's Fashion"},
    {_id: "112" , title: "Health & Household"},
    {_id: "113" , title: "Home & Kitchen"},
    {_id: "114" , title: "Industrial & Scientific"},
    {_id: "115" , title: "Kindle Store"},
    {_id: "116" , title: "Luggage"},
    {_id: "117" , title: "Men's Fashion"},
    {_id: "118" , title: "Movies & TV"},
    {_id: "119" , title: "Music, CDs & Vinyl"},
    {_id: "120" , title: "Pet Supplies"},
    {_id: "121" , title: "Prime Video"},
    {_id: "122" , title: "Software"},
    {_id: "123" , title: "Sports & Outdoors"},
    {_id: "124" , title: "Tools & Home Improvement"},
    {_id: "125" , title: "Toys & Gamed"},
    {_id: "126" , title: "Video Games"},
    {_id: "127 " , title: "Women's Fashion"},
  ]


  export const footerMiddleList = [
    {title:"Get to Know Us" , 
      items:["Careers", "Blog", "About Amazon", "Investor Relations", "Amazon Devices", "Amazon Science"] },
    {title:"Make Money with Us" , 
      items:["Sell products on Amazon", "Sell on Amazon Business", "Sell apps on Amazon", "Become an Affiliate", " Advertise Your Products", "Self-Publish with Us", "Host an Amazon Hub", "›See More Make Money with Us"] },
    {title:"Amazon Payment Products" , 
      items:["Amazon Business Card", "Shop with Points", "Reload Your Balance", "Amazon Currency Converter"] },
    {title:"Let Us Help You" , 
      items:["Amazon and COVID-19", "Your Account", "Your Orders", "Shipping Rates & Policies", "Returns & Replacements", "Manage Your Content and Devices", "Help"] }
  ]

  export const footerBottomItem = [
    {title: "Amazon Music", des:"Stream millions of songs"},
    {title: "Amazon Business", des:"Everything For Your Business" },
    {title: "IMDbPro", des:"Get Info Entertainment Professionals Need"},
    {title: "Amazon Ads", des:"Reach customers wherever they spend their time"},
    {title: "AmazonGlobal", des:"Ship Orders Internationally"},
    {title: "Kindle Direct Publishing", des:"Indie Digital & Print Publishing Made Easy"},
    {title: "eero WiFi", des:"Stream 4K Video in Every Room"},
    {title: "6pm", des:"Score deals on fashion brands"},
    {title: "Amazon Web Services", des:"Scalable Cloud Computing Services"},
    {title: "Prime Video Direct", des:"Video Distribution Made Easy"},
    {title: "Blink", des:"Smart Security for Every Home"},
    {title: "AbeBooks", des:"Books, art & collectibles"},
    {title: "Audible", des:"Listen to Books & Original Audio Performances"},
    {title:"Shopbop", des:"Designer Fashion Brands"},
    {title:"Neighbors App", des:"Real-Time Crime & Safety Alerts"},
    {title:"ACX", des:"Audiobook Publishing Made Easy"},
    {title:"Box Office Mojo", des:"Find Movie Box Office Data"},
    {title:"Woot!", des:"Deals and Shenanigans"},
    {title:" Amazon Subscription Boxes", des:"Top subscription boxes  right to your door"},
    {title:"Sell on Amazon", des:"Start a Selling Account"},
    {title:"Goodreads", des:"Book reviews & recommendations"},
    {title:"Zappos", des:"Shoes & Clothing"},
    {title:"PillPack", des:"Pharmacy Simplified"},
    {title:"Veeqo", des:"Shipping Software Inventory Management"},
    {title:"IMDb", des:"Movies, TV & Celebrities"},
    {title:"Ring", des:"Smart Home Security Systems"},
  ]